(function($){Drupal.Views={};Drupal.behaviors.viewsTabs={attach:function(context){if($.viewsUi&&$.viewsUi.tabs){$('#views-tabset').once('views-processed').viewsTabs({selectedClass:'active'});}
$('a.views-remove-link').once('views-processed').click(function(event){var id=$(this).attr('id').replace('views-remove-link-','');$('#views-row-'+id).hide();$('#views-removed-'+id).attr('checked',true);event.preventDefault();});$('a.display-remove-link').addClass('display-processed').click(function(){var id=$(this).attr('id').replace('display-remove-link-','');$('#display-row-'+id).hide();$('#display-removed-'+id).attr('checked',true);return false;});}};Drupal.Views.parseQueryString=function(query){var args={};var pos=query.indexOf('?');if(pos!=-1){query=query.substring(pos+1);}
var pairs=query.split('&');for(var i in pairs){if(typeof(pairs[i])=='string'){var pair=pairs[i].split('=');if(pair[0]!='q'&&pair[1]){args[decodeURIComponent(pair[0].replace(/\+/g,' '))]=decodeURIComponent(pair[1].replace(/\+/g,' '));}}}
return args;};Drupal.Views.parseViewArgs=function(href,viewPath){if(Drupal.settings.pathPrefix){var viewPath=Drupal.settings.pathPrefix+viewPath;}
var returnObj={};var path=Drupal.Views.getPath(href);if(viewPath&&path.substring(0,viewPath.length+1)==viewPath+'/'){var args=decodeURIComponent(path.substring(viewPath.length+1,path.length));returnObj.view_args=args;returnObj.view_path=path;}
return returnObj;};Drupal.Views.pathPortion=function(href){var protocol=window.location.protocol;if(href.substring(0,protocol.length)==protocol){href=href.substring(href.indexOf('/',protocol.length+2));}
return href;};Drupal.Views.getPath=function(href){href=Drupal.Views.pathPortion(href);href=href.substring(Drupal.settings.basePath.length,href.length);if(href.substring(0,3)=='?q='){href=href.substring(3,href.length);}
var chars=['#','?','&'];for(var i in chars){if(href.indexOf(chars[i])>-1){href=href.substr(0,href.indexOf(chars[i]));}}
return href;};})(jQuery);;(function($){Drupal.progressBar=function(id,updateCallback,method,errorCallback){var pb=this;this.id=id;this.method=method||'GET';this.updateCallback=updateCallback;this.errorCallback=errorCallback;this.element=$('<div class="progress" aria-live="polite"></div>').attr('id',id);this.element.html('<div class="bar"><div class="filled"></div></div>'+
'<div class="percentage"></div>'+
'<div class="message">&nbsp;</div>');};Drupal.progressBar.prototype.setProgress=function(percentage,message){if(percentage>=0&&percentage<=100){$('div.filled',this.element).css('width',percentage+'%');$('div.percentage',this.element).html(percentage+'%');}
$('div.message',this.element).html(message);if(this.updateCallback){this.updateCallback(percentage,message,this);}};Drupal.progressBar.prototype.startMonitoring=function(uri,delay){this.delay=delay;this.uri=uri;this.sendPing();};Drupal.progressBar.prototype.stopMonitoring=function(){clearTimeout(this.timer);this.uri=null;};Drupal.progressBar.prototype.sendPing=function(){if(this.timer){clearTimeout(this.timer);}
if(this.uri){var pb=this;$.ajax({type:this.method,url:this.uri,data:'',dataType:'json',success:function(progress){if(progress.status==0){pb.displayError(progress.data);return;}
pb.setProgress(progress.percentage,progress.message);pb.timer=setTimeout(function(){pb.sendPing();},pb.delay);},error:function(xmlhttp){pb.displayError(Drupal.ajaxError(xmlhttp,pb.uri));}});}};Drupal.progressBar.prototype.displayError=function(string){var error=$('<div class="messages error"></div>').html(string);$(this.element).before(error).hide();if(this.errorCallback){this.errorCallback(this);}};})(jQuery);;(function($){Drupal.ajax.prototype.originalBeforeSerialize=Drupal.ajax.prototype.beforeSerialize;Drupal.ajax.prototype.beforeSerialize=function(element,options){if(options.url&&options.url.indexOf('/views/ajax')!==-1&&Drupal.settings.viewsAjaxGet&&$.inArray(options.data.view_name,Drupal.settings.viewsAjaxGet)!==-1){if(this.form){var settings=this.settings||Drupal.settings;Drupal.detachBehaviors(this.form,settings,'serialize');}
options.type='GET';return;}
return this.originalBeforeSerialize(element,options);};})(jQuery);;(function($){Drupal.behaviors.ViewsAjaxView={};Drupal.behaviors.ViewsAjaxView.attach=function(){if(Drupal.settings&&Drupal.settings.views&&Drupal.settings.views.ajaxViews){$.each(Drupal.settings.views.ajaxViews,function(i,settings){Drupal.views.instances[i]=new Drupal.views.ajaxView(settings);});}};Drupal.views={};Drupal.views.instances={};Drupal.views.ajaxView=function(settings){var selector='.view-dom-id-'+settings.view_dom_id;this.$view=$(selector);var ajax_path=Drupal.settings.views.ajax_path;if(ajax_path.constructor.toString().indexOf("Array")!=-1){ajax_path=ajax_path[0];}
var queryString=window.location.search||'';if(queryString!==''){var queryString=queryString.slice(1).replace(/q=[^&]+&?|&?render=[^&]+/,'');if(queryString!==''){queryString=((/\?/.test(ajax_path))?'&':'?')+queryString;}}
this.element_settings={url:ajax_path+queryString,submit:settings,setClick:true,event:'click',selector:selector,progress:{type:'throbber'}};this.settings=settings;this.$exposed_form=$('#views-exposed-form-'+settings.view_name.replace(/_/g,'-')+'-'+settings.view_display_id.replace(/_/g,'-'));this.$exposed_form.once(jQuery.proxy(this.attachExposedFormAjax,this));this.links=[];this.$view.filter(jQuery.proxy(this.filterNestedViews,this)).once(jQuery.proxy(this.attachPagerAjax,this));var self_settings=this.element_settings;self_settings.event='RefreshView';this.refreshViewAjax=new Drupal.ajax(this.selector,this.$view,self_settings);};Drupal.views.ajaxView.prototype.attachExposedFormAjax=function(){var button=$('input[type=submit], button[type=submit], input[type=image]',this.$exposed_form);button=button[0];$(button).click(function(){if(Drupal.autocompleteSubmit){Drupal.autocompleteSubmit();}});this.exposedFormAjax=new Drupal.ajax($(button).attr('id'),button,this.element_settings);};Drupal.views.ajaxView.prototype.filterNestedViews=function(){return!this.$view.parents('.view').length;};Drupal.views.ajaxView.prototype.attachPagerAjax=function(){this.$view.find('ul.pager > li > a, th.views-field a, .attachment .views-summary a').each(jQuery.proxy(this.attachPagerLinkAjax,this));};Drupal.views.ajaxView.prototype.attachPagerLinkAjax=function(id,link){var $link=$(link);var viewData={};var href=$link.attr('href');$.extend(viewData,this.settings,Drupal.Views.parseQueryString(href),Drupal.Views.parseViewArgs(href,this.settings.view_base_path));$.extend(viewData,Drupal.Views.parseViewArgs(href,this.settings.view_base_path));this.element_settings.submit=viewData;this.pagerAjax=new Drupal.ajax(false,$link,this.element_settings);this.links.push(this.pagerAjax);};Drupal.ajax.prototype.commands.viewsScrollTop=function(ajax,response,status){var offset=$(response.selector).offset();var scrollTarget=response.selector;while($(scrollTarget).scrollTop()==0&&$(scrollTarget).parent()){scrollTarget=$(scrollTarget).parent();}
if(offset.top-10<$(scrollTarget).scrollTop()){$(scrollTarget).animate({scrollTop:(offset.top-10)},500);}};})(jQuery);;(function($){Drupal.behaviors.gd_infinite_scroll={attach:function(){var gd_settings=Drupal.settings.gd_infinite_scroll;if(typeof gd_settings=='object'){for(var key in gd_settings){var $content_selector=$(gd_settings[key].content_selector).not('.gd-infinite-scroll-initialized');if($content_selector[0]){$content_selector.addClass('gd-infinite-scroll-initialized');this.init_gd_infinite_scroll(key,gd_settings[key]);}}}},init_gd_infinite_scroll:function(autopager_id,settings){var content_selector=settings.content_selector;var items_selector=settings.content_selector+' '+settings.items_selector;var pager_selector=settings.pager_selector;var next_selector=settings.next_selector;var img_location=settings.content_selector;var img_path=settings.img_path;var load_more=settings.load_more;var load_more_markup=settings.load_more_markup;var ajax_pager=settings.ajax_pager;var img='<div class="gd_infinite_scroll-ajax-loader"><img src="'+img_path+'" alt="'+Drupal.t('Loading')+'..."></div>';var $this=this;if(!$(content_selector)[0]){return;}
var autoloading=true;var load_more_button=$('<a></a>');if(load_more){autoloading=false;load_more_button=$(load_more_markup);}
if(ajax_pager){autoloading=false;$(pager_selector+' a').not('.gd-infinite-scroll-ajax-initialized').click(function(e){var href=$(this).attr('href');$(pager_selector+' a').not(this).removeClass('active');$(pager_selector+' li').removeClass('pager-current');$(this).addClass('active').parent().addClass('pager-current');$.get(href,function(data){var nextPage=$('<div/>').append(data.replace(/<script(.|\s)*?\/script>/g,"")),nextContent=nextPage.find(content_selector);$(content_selector).replaceWith(nextContent).addClass('gd-infinite-scroll-initialized');Drupal.attachBehaviors($(content_selector)[0]);});e.preventDefault();}).addClass('gd-infinite-scroll-ajax-initialized');}
else{$(pager_selector).hide();this.autopager(autopager_id,{autoLoad:autoloading,appendTo:content_selector,content:items_selector,link:next_selector,page:0,start:function(){$(img_location).after(img);},load:function(current,next){$(content_selector).next('div.gd_infinite_scroll-ajax-loader').remove();Drupal.attachBehaviors(this);if(load_more&&!next.url){load_more_button.hide();}}});}
if(!load_more&&!ajax_pager&&$(items_selector)[0]){var prev_content_height=$(content_selector).height();do{var last=$(items_selector).filter(':last');if(last.offset().top+last.height()<$(document).scrollTop()+$(window).height()){last=$(items_selector).filter(':last');$this.load(autopager_id);}
else{break;}}
while($(content_selector).height()>prev_content_height);}
else if($(next_selector)[0]&&load_more){load_more_button.addClass('gd-infinite-scroll-load-more').appendTo($(img_location).parent()).click(function(e){$this.load(autopager_id);e.preventDefault();});}},state:{},_optionsDefault:{autoLoad:true,page:1,content:'.content',link:'a[rel=next]',insertBefore:null,appendTo:null,start:function(){},load:function(){},disabled:false},setState:function(autopager_id,values){for(var key in values){this.state[autopager_id][key]=values[key];}},autopager:function(autopager_id,options){var _options=$.extend({},this._optionsDefault,options);var _content=$(_options.content).filter(':last');if(_content.length){if(!_options.insertBefore&&!_options.appendTo){var insertBefore=_content.next();if(insertBefore.length){this.setOption('insertBefore',insertBefore);}
else{this.setOption('appendTo',_content.parent());}}}
this.state[autopager_id]={content:_content,active:false,options:{},},this.option(autopager_id,_options);this.setUrl(autopager_id);},loadOnScroll:function(autopager_id,e){var content=this.state[autopager_id]['content'];if(content.offset().top<$(document).scrollTop()+$(window).height()){this.load(autopager_id);}},load:function(autopager_id){if(this.state[autopager_id]['active']||!this.state[autopager_id]['nextUrl']||this.option(autopager_id,'disabled')){return;}
this.setState(autopager_id,{active:true});var fn=this.option(autopager_id,'start');fn(this.currentHash(autopager_id),this.nextHash(autopager_id));$.get(this.state[autopager_id]['nextUrl'],this.insertContent.bind(this,autopager_id));return this;},insertContent:function(autopager_id,res){var _options=this.state[autopager_id]['options'],nextPage=$('<div/>').append(res.replace(/<script(.|\s)*?\/script>/g,"")),nextContent=nextPage.find(_options.content);this.setOption(autopager_id,'page',_options.page+1);this.setUrl(autopager_id,nextPage);if(nextContent.length){if(_options.insertBefore){nextContent.insertBefore(_options.insertBefore);}else{nextContent.appendTo(_options.appendTo);}
_options.load.call(nextContent.get(),this.currentHash(autopager_id),this.nextHash(autopager_id));this.state[autopager_id]['content']=nextContent.filter(':last');}
this.state[autopager_id]['active']=false;},currentHash:function(autopager_id){var _options=this.state[autopager_id]['options'];return{page:_options.page,url:this.state[autopager_id]['currentUrl']};},nextHash:function(autopager_id){var _options=this.state[autopager_id]['options'];return{page:_options.page+1,url:this.state[autopager_id]['nextUrl']};},setUrl:function(autopager_id,context){var values={};values.currentUrl=this.state[autopager_id]['nextUrl']||window.location.href;values.nextUrl=$(this.option(autopager_id,'link'),context).attr('href');this.setState(autopager_id,values);},option:function(autopager_id,key,value){var _options=key;var $this=this;if(typeof key==="string"){if(value===undefined){return this.state[autopager_id]['options'][key];}
_options={};_options[key]=value;}
$.each(_options,function(key,value){$this.setOption(autopager_id,key,value);});return this;},setOption:function(autopager_id,key,value){switch(key){case 'autoLoad':if(value&&!this.state[autopager_id]['options']['autoLoad']){$(window).scroll(this.loadOnScroll.bind(this,autopager_id));}else if(!value&&this.state[autopager_id]['options']['autoLoad']){$(window).unbind('scroll',this.loadOnScroll);}
break;case 'insertBefore':if(value){this.state[autopager_id]['options']['appendTo']=null;}
break
case 'appendTo':if(value){this.state[autopager_id]['options']['insertBefore']=null;}
break}
this.state[autopager_id]['options'][key]=value;},enable:function(autopager_id){this.setOption(autopager_id,'disabled',false);return this;},disable:function(autopager_id){this.setOption(autopager_id,'disabled',true);return this;}}})(jQuery);;